apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gridvo-wechat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gridvo-wechat
    spec:
      containers:
      - name: gridvo-wechat
        image: 10.0.2.62:5000/gridvo/gridvo-wechat:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: ZK_TRACER_HTTP
          value: "true"
        - name: IS_DEBUG
          value: "true"
             
