apiVersion: v1
kind: Service
metadata:
  labels:
    name: gridvo-wechat
  name: gridvo-wechat
  namespace: gridvo
spec:
  selector: 
    name: gridvo-wechat
  ports:
     - port: 80
       targetPort: 3001
