apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: gridvo-wechat
  name: gridvo-wechat
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gridvo-wechat
    spec:
      containers:
      - name: gridvo-wechat
        image: 10.0.3.31:5000/gridvo/gridvo-wechat:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_SERVICE_HOST
          value: "mongodb"
        - name: MONGODB_SERVICE_PORT
          value: "27017"
        - name: ZOOKEEPER_SERVICE_HOST
          value: "zookeeper"
        - name: ZOOKEEPER_SERVICE_PORT
          value: "2181"
        - name: ZIPKIN_SERVICE_HOST
          value: "zipkin"
        - name: ZIPKIN_HTTP_TRANSPORT_PORT
          value: "31011"
        - name: ZK_TRACER_HTTP
          value: "true"
        - name: IS_DEBUG
          value: "true"
        - name: SG_WECHAT_PORTAL_DOMAIN
          value: "pascal.gridvo.com"
