version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
     - "27017:27017"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gridvo-wechat:
    build: .
    image: gridvo/gridvo-wechat:dev
    container_name: gridvo-wechat
    depends_on:
     - zookeeper
     - kafka
     - mongodb
    environment:
      MONGODB_SERVICE_HOST: mongodb
      MONGODB_SERVICE_PORT: 27017
      ZOOKEEPER_SERVICE_HOST: zookeeper
      ZOOKEEPER_SERVICE_PORT: 2181
  unittest:
    image: node:latest
    container_name: unittest
    volumes_from:
     - gridvo-wechat
    depends_on:
     - zookeeper
     - kafka
     - mongodb
     - gridvo-wechat
    environment:
      MONGODB_SERVICE_HOST: mongodb
      MONGODB_SERVICE_PORT: 27017
      ZOOKEEPER_SERVICE_HOST: zookeeper
      ZOOKEEPER_SERVICE_PORT: 2181
    working_dir: /home/gridvo-wechat
    command: npm test